version: '3'

services:
  ssl-proxy-web:
    build:
      context: .
      dockerfile: DockerfileSSLProd
    ports:
      - 443:443

  mqtt-web:
    build:
      context: .
      dockerfile: DockerfileProd
    ports:
      - 4200:80
