version: '3'

services:
  ssl-proxy-web:
    build:
      context: .
      dockerfile: DockerfileSSL
    ports:
      - 443:443

  mqtt-web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 4200:4200
