version: '3'

services:
  pingpong-web:
    image: ${IMAGE_REPO}pingpong-web:${VERSION}
    hostname: pingpong-web
    networks:
      - frontend_network
      - backend_network

networks:
  frontend_network:
    external: true
  backend_network:
    external: true