version: '3'

services:  
  service-tests:
    image: service.tests
    container_name: service-tests
    build:
      context: .
      dockerfile: Dockerfile_Test
    networks:
      - backend_network
      - frontend_network

networks:
  backend_network:
    external: true
  frontend_network:
    external: true